FabricMC/tiny-remapper

src/main/java/net/fabricmc/tinyremapper/TinyUtils.java

Previously mapped member descriptors to the `to` namespace instead, which isn't how `IMappingProvider` is designed to take them (as it would be odd to have the `from` namespace name with the `to` namespace descriptor).

Fix member descriptors when the from namespace isn't first

---

src/main/java/net/fabricmc/tinyremapper/AsmClassRemapper.java

Previously `AsmClassRemapper` could create local var names which are keywords or literals, or it would not consider existing variable names which are keywords or literals as invalid.
It now uses [SourceVersion.isName](https://docs.oracle.com/javase/8/docs/api/javax/lang/model/SourceVersion.html#isName-java.lang.CharSequence-) to detect invalid names, whose behavior sadly depends on the running Java version. In Java 9(+) this can be solved by using the [method overload](https://docs.oracle.com/en/java/javase/11/docs/api/java.compiler/javax/lang/model/SourceVersion.html#isName(java.lang.CharSequence,javax.lang.model.SourceVersion)) which accepts a `SourceVersion`.
[test.zip](https://github.com/FabricMC/tiny-remapper/files/4051303/test.zip) contains a class file for which tiny-remapper would …

Prevent keywords or literals being used as local var names

---

src/main/java/net/fabricmc/tinyremapper/AsmClassRemapper.java

Previously local variables and arguments whose generated name was a keyword would instead get the unspecific names "lv" or "arg" (see also #30).
This pull request changes it so the generated name followed by a '_' (similar to how CFR does it) is used.
With `_` becoming a keyword in Java 9, `_` would become `__` (which is valid). Should this get a special case?

Append '_' to local var names in case they are keywords

---

src/main/java/net/fabricmc/tinyremapper/AsmClassRemapper.java

Ignorable chars (`Character.isIdentifierIgnorable`) are ignored as part of identifiers (cannot be leading, but can be in between and trailing) when compiling. They can therefore normally not appear in a class file unless it was modified. Since they cannot be represented in source (and could easily cause identifier collisions), identifiers containing them are now considered invalid.
This was only added to the JLS for Java 10 (see [JDK-6214519](https://bugs.openjdk.java.net/browse/JDK-6214519)), however the behavior also exists in earlier versions.
Demonstration of the issue:
1. Download [IdentifierIgnorable.class.txt](https://github.com/FabricMC/tiny-remapper/files/4566792/IdentifierIgnorable.class.txt) (remove `.txt`, that is only to make GitHub happy)
2. Use Tiny Remapper and let it …

Fix variable names containing ignorable chars not being renamed

---

.gitignore
src/main/java/net/fabricmc/tinyremapper/Main.java

This relates to, but is technically separate from #44. That issue was the motivation for this PR.
Other than determining threading issues and being able to mitigate them when they happen, this is nice to have in general from a user experience standpoint.
I also added `.idea/` to `.gitignore` because that was annoying me.

Allow threads to be configurable from the CLI

---

build.gradle

They're used in the "API" parts of TR (api package and TinyRemapper class), so it'd make sense to expose them at compile time to dependents.

Move asm and asm-commons dependencies to 'api'

---

src/main/java/net/fabricmc/tinyremapper/TinyUtils.java

Fixes support for some jar mapping and merging stuff in cases related to pre 1.3.1 versions, which would be really nice to get working in upstream loom at some point, and this is the 0th step for getting that to be a reality.

Make V1 reader not discard trailing empty values

---

src/main/java/net/fabricmc/tinyremapper/MetaInfFixer.java

Uses the same workaround as in OutputConsumerPath

Avoid requiring identical fs in MetaInfFixer

---

src/main/java/net/fabricmc/tinyremapper/extension/mixin/common/data/Message.java
src/main/java/net/fabricmc/tinyremapper/extension/mixin/soft/annotation/injection/CommonInjectionAnnotationVisitor.java
src/main/java/net/fabricmc/tinyremapper/extension/mixin/soft/annotation/injection/DescAnnotationVisitor.java

Current drawbacks:
- No "1:N" mappings (which may be the case for multiple owner classes)
- No support for `@Desc` within `@At` (custom injection points would make it difficult to impossible to differ between method and field and thus it requires a different philosophy. However for my purposes I don't need `@Desc` in `@At` just yet)
These drawbacks would require a novel idea to get resolved and in my opinion result from the fact that `@Desc` was not meant to get remapped.
I believe I have briefly mentioned regex support within explicit target selectors, which in theory would allow to condense 1:N mappings down into a single regex string but even then we would get behavioral changes. Plus I don't know how far the capabilities of regex within explicit target selectors reach.
As such the …

Implement barebone support for Mixin's `@Desc`

---

src/main/java/net/fabricmc/tinyremapper/AsmClassRemapper.java
src/main/java/net/fabricmc/tinyremapper/Main.java
src/main/java/net/fabricmc/tinyremapper/TinyRemapper.java

I've recently ran up against #26 in a project of mine - I get so much log spam due to tiny-remapper finding groovy indy instructions that it cannot remap that it is impossible to see any actual issues in the logs. I would like some way of turning off that warning for specific indy instructions, similar to what is already done for string concatenation. This PR adds a system property, `net.fabricmc.tinyremapper.knownindybsm` (this could definitely change, I'm by no means sold on it) for providing a list of instructions that tiny-remapper can safely assume do not need to be remapped.
If you think there may be a better approach to this than a system property, please let me know, and I can see about implementing that.

Add CLI option to ignore invokedynamic types

---

build.gradle

Allows downstream projects to use newer java versions when depending on tiny-remapper.
My company's product uses tiny-remapper as a tool, but cannot use newer versions of the java toolchain because running tiny-remapper fails as the old version of asm does not recognize newer java class file versions.

Update asm dependency

---

src/main/java/net/fabricmc/tinyremapper/extension/mixin/MixinExtension.java
src/main/java/net/fabricmc/tinyremapper/extension/mixin/hard/HardTargetMixinClassVisitor.java
src/main/java/net/fabricmc/tinyremapper/extension/mixin/hard/HardTargetMixinFieldVisitor.java
src/main/java/net/fabricmc/tinyremapper/extension/mixin/hard/HardTargetMixinMethodVisitor.java
src/main/java/net/fabricmc/tinyremapper/extension/mixin/hard/annotation/AccessorAnnotationVisitor.java
src/main/java/net/fabricmc/tinyremapper/extension/mixin/hard/annotation/ImplementsAnnotationVisitor.java
src/main/java/net/fabricmc/tinyremapper/extension/mixin/hard/annotation/InvokerAnnotationVisitor.java
src/main/java/net/fabricmc/tinyremapper/extension/mixin/hard/annotation/OverwriteAnnotationVisitor.java
src/main/java/net/fabricmc/tinyremapper/extension/mixin/hard/annotation/ShadowAnnotationVisitor.java

When remapping a jar with many mixins (sponge jar) I discovered that some members were not remapped properly. Which members were not remapped was fully random and changed each time I re execute the task.
After some debugging I found that multiple threads are writing to the `tasks` list in `MixinExtension` but this list is not thread-safe. I tried replacing it with a thread-safe collection and it fixed my problem. Here is the fix.

Fix random mixin members not getting remapped due to concurrency issues

---

src/main/java/net/fabricmc/tinyremapper/TinyRemapper.java
src/main/java/net/fabricmc/tinyremapper/extension/mixin/MixinExtension.java

This can be used in Loom to filter which dependencies will have remapped mixins based on the presence of a refmap file.

Support extensions + mixin extension per input tag

---

build.gradle
src/main/java/net/fabricmc/tinyremapper/TinyUtils.java

Now uses Mapping-IO under the hood for reading mappings. I didn't touch `IMappingProvider` yet, since this would 1) require larger internal changes (harder for you to review) and 2) break existing API surfaces. I'll tackle this in a future PR.

Switch to Mapping-IO

---

src/main/java/net/fabricmc/tinyremapper/ClassInstance.java
src/test/java/net/fabricmc/tinyremapper/ClassInstanceTest.java

The previous logic would add the same tag multiple times into the array, dropping new tags.

Fix and test ClassInstance.addInputTags

---

src/main/java/net/fabricmc/tinyremapper/TinyUtils.java

Since constructing a `IMappingProvider` manually can be tricky due to TR not handling null values gracefully. Useful for https://github.com/FabricMC/fabric-loader/pull/912.

Provide `MappingTreeView` -> `IMappingProvider` converter

---

src/main/java/net/fabricmc/tinyremapper/extension/mixin/soft/annotation/injection/DescAnnotationVisitor.java

Fixes #135
--
In hindsight I'm a little bit surprised that this didn't end up producing mangled bytecode since visitArray would be called while visitEnd would never be called. However, the result was invalid either way, so this change resolves that issue at the very least, though the other (known) shortfalls of how `@Desc` is being remapped in tiny-remapper remain unaddressed. Though given that this rather serious bug remained unnoticed for a bit longer than a year is a good indicator that investing all too much resources in more nuanced edge-cases is a bit … overreacting.

Fix Desc.args being stripped in the remapping process

---

src/main/java/net/fabricmc/tinyremapper/TinyUtils.java

This doesn't change behavior, since entries with duplicated names wouldn't have been forwarded by the chained `MappingAdapter` anyway, but it might provide a small speed improvement.
Also changes a misleading method name.

Fix ` MappingSourceNsSwitch` not dropping entries with missing destination names

---

src/main/java/net/fabricmc/tinyremapper/Main.java
src/main/java/net/fabricmc/tinyremapper/TinyRemapper.java
src/main/java/net/fabricmc/tinyremapper/extension/mixin/MixinExtension.java
src/main/resources/META-INF/services/net.fabricmc.tinyremapper.TinyRemapper$CLIExtensionProvider

This could be used to add Kotlin remapping to the CLI without adding it directly to TR.

Allow enabling extensions from the classpath via CLI args

---

src/main/java/net/fabricmc/tinyremapper/extension/mixin/soft/data/MemberInfo.java
src/test/java/net/fabricmc/tinyremapper/extension/mixin/soft/data/MemberInfoTest.java

Fixes #137
Wildcard targets should not specify a desc.
When remapping the name of the first matching method will be used.

Fix wildcard targets

---

build.gradle

Hi,
I wanted to update ASM to 9.7 because otherwise paperweight is failing (its using TR).
I am not sure how to properly test this change as I am not that familiar with TR so I just ran the unit / integration tests.
```
Caused by: java.lang.RuntimeException: error analyzing X/WorldRegion.class from X
at net.fabricmc.tinyremapper.TinyRemapper.analyze(TinyRemapper.java:604)
at net.fabricmc.tinyremapper.TinyRemapper.access$400(TinyRemapper.java:71)
at net.fabricmc.tinyremapper.TinyRemapper$2.visitFile(TinyRemapper.java:553)
at net.fabricmc.tinyremapper.TinyRemapper$2.visitFile(TinyRemapper.java:549)
at java.base/java.nio.file.Files.walkFileTree(Files.java:2810)
at java.base/java.nio.file.Files.walkFileTree(Files.java:2881)
at net.fabricmc.tinyremapper.TinyRemapper.readFile(TinyRemapper.java:5 …
```

chore: upgrade asm to 9.7 to support java 23

---

src/main/java/net/fabricmc/tinyremapper/AsmRemapper.java
src/main/java/net/fabricmc/tinyremapper/TinyRemapper.java

Not sure why this wasn't enabled yet, from my (arguably limited) testing it looks like everything's working correctly.

Support local variable remapping

---

src/main/java/net/fabricmc/tinyremapper/extension/mixin/common/data/Annotation.java
src/main/java/net/fabricmc/tinyremapper/extension/mixin/common/data/AnnotationElement.java
src/main/java/net/fabricmc/tinyremapper/extension/mixin/soft/SoftTargetMixinMethodVisitor.java
src/main/java/net/fabricmc/tinyremapper/extension/mixin/soft/annotation/injection/AtAnnotationVisitor.java
src/main/java/net/fabricmc/tinyremapper/extension/mixin/soft/annotation/injection/AtMemberMappable.java
src/main/java/net/fabricmc/tinyremapper/extension/mixin/soft/annotation/injection/DefinitionAnnotationVisitor.java
src/main/java/net/fabricmc/tinyremapper/extension/mixin/soft/annotation/injection/DefinitionsAnnotationVisitor.java

Adds support for remapping `method` and `field` strings in `@Definition`s and their container annotation `@Definitions`.
See https://github.com/LlamaLad7/MixinExtras/wiki/Expressions

MixinExtras `@Expression` support
